name: Crowdin Contributors Action

on:
  # When you push to the `main` branch
  push:
    branches: [ main ]
  # And optionally, once every 12 hours
  schedule:
    - cron: '0 */12 * * *' # https://crontab.guru/#0_*/12_*_*_*
  # To manually run this workflow
  workflow_dispatch:

jobs:
  crowdin-contributors:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Crowdin Contributors table
      uses: andrii-bodnar/action-crowdin-contributors@v2
      with:
          contributors_per_line: 5
          max_contributors: 10000
          image_size: 100
          min_words_contributed: 1
          include_languages: true
          placeholder_start: <!-- CROWDIN-CONTRIBUTORS-LIST:START -->
          placeholder_end: <!-- CROWDIN-CONTRIBUTORS-LIST:END -->
          crowdin_project_link: https://crowdin.com/project/shortremover
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
